export const SET_YEAR_SORTING = 'SET_YEAR_SORTING'
export const SET_SUPPLIER_SORTING = 'SET_SUPPLIER_SORTING'
export const SET_PRODUCT_SORTING = 'SET_PRODUCT_SORTING'
export const SET_CLIENT_SORTING = 'SET_CLIENT_SORTING'